[versions]
kotlin = "2.4.20"
agp = "9.4.1"
composeBom = "2026.09.00"
coreKtx = "1.19.1"
activityCompose = "1.13.0"
coroutinesAndroid = "1.11.0"
junit = "4.13.2"
dokkaCli = "2.0.0"
ktlintCli = "1.8.0"

[libraries]
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-runtime-saveable = { group = "androidx.compose.runtime", name = "runtime-saveable" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutinesAndroid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ktlint-cli = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlintCli" }
dokka-cli = { group = "org.jetbrains.dokka", name = "dokka-cli", version.ref = "dokkaCli" }
dokka-base = { group = "org.jetbrains.dokka", name = "dokka-base", version.ref = "dokkaCli" }
dokka-analysis = { group = "org.jetbrains.dokka", name = "analysis-kotlin-symbols", version.ref = "dokkaCli" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
